# Generated by Django 5.0.2 on 2024-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('event', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sport', models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Tennis', 'Tennis'), ('Swimming', 'Swimming')], max_length=100)),
            ],
        ),
    ]
